baseURL = "https://vtsugi1.github.io/personal-website-hugo/"
languageCode = "en-us"
title = "Vinicius Tsugi | Data & Analytics Leader"
theme = "PaperMod"

[params]
  author = "Vinicius Tsugi"
  description = "Principal Analyst at SEEK with 15+ years of experience in Digital Analytics and Cloud Analytics platforms."
  ShowReadingTime = false
  ShowToc = true
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableScrollToTop = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3