baseURL = 'https://vtsugi1.github.io/'
languageCode = 'pt-BR'
title = 'Clínica de Psicologia'
theme = 'quint'

[params]
  author = 'Clínica de Psicologia [Nome]'
  description = 'Site institucional da Clínica de Psicologia [Nome].'

[menu]
  [[menu.main]]
    identifier = 'atendimento'
    name = 'Atendimento Psicológico'
    url = '/atendimento/'
    weight = 1

  [[menu.main]]
    identifier = 'supervisao'
    name = 'Supervisão Clínica'
    url = '/supervisao/'
    weight = 2

  [[menu.main]]
    identifier = 'acao-social'
    name = 'Ação Social'
    url = '/acao-social/'
    weight = 3

  [[menu.main]]
    identifier = 'grupos-terapeuticos'
    name = 'Grupos Terapêuticos'
    url = '/grupos-terapeuticos/'
    weight = 4
    
  [[menu.main]]
    identifier = 'quem-somos'
    name = 'Quem Somos'
    url = '/quem-somos/'
    weight = 5

  [[menu.main]]
    identifier = 'contato'
    name = 'Contato'
    url = '/contato/'
    weight = 6

