baseURL = "https://vtsugi1.github.io/personal-website-hugo/"
languageCode = "en-us"
title = "Vini's Data Engineering Portfolio"
theme = "PaperMod"

[params]
  author = "Vini"
  description = "A personal website showcasing my work as a data engineer."
  ShowReadingTime = false
  ShowToc = false
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableScrollToTop = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
